program: train.py
method: bayes

metric:
  name: eval/mean/AUC
  goal: maximize

parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0002
    max: 0.002

  batch_size:
    values: [64, 128, 256]

  num_layers:
    values: [2, 3, 4]

  num_heads:
    values: [4, 8, 16]

  dropout:
    values: [0.0, 0.1, 0.2]

  max_parameters:
    value: 60000000

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --config
  - configs/sweeps/bases/amazon_electronics_x1.yaml
  - --wandb
  - --wandb_project
  - MixFormer
  - --wandb_group_name
  - amazon-electronics-main-sweep
  - --wandb_tags
  - formal,amazon,main-sweep
  - ${args}